# RoboTHOR + Habitat 2022 Challenge Target Objects
- AlarmClock
- Apple
- BaseballBat
- BasketBall
- Bed
- Bowl
- Chair
- GarbageCan
- HousePlant
- Laptop
- Mug
- Sofa
- SprayBottle
- Television
- Toilet
- Vase

# - AlarmClock
# - Apple
# - Book
# - Bottle
# - Bowl
# - Box
# - CD
# - Candle
# - CellPhone
# - CreditCard
# - Cup
# - DishSponge
# - Egg
# - Fork
# - Kettle
# - KeyChain
# - Knife
# - Ladle
# - Laptop
# - Mug
# - Newspaper
# - Pan
# - PaperTowelRoll
# - Pen
# - Pencil
# - PepperShaker
# - Pillow
# - Plate
# - Pot
# - Potato
# - RemoteControl
# - SaltShaker
# - SoapBottle
# - Spatula
# - Spoon
# - SprayBottle
# - Statue
# - TeddyBear
# - TissueBox
# - ToiletPaper
# - Tomato
# - Vase
# - Watch
# - WineBottle

